[package]
name = "ac-plugin-pfngp"
version = "0.1.0"
authors = ["loxygenk <loxygen.k@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
autoclip-core = "0.1.0"
gpgme = "0.9.2"
